project:
  type: website

website:
  title: "Trends in Global Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - plots.qmd
      - models.qmd
      - sources.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

